---
# tasks file for worker_node

  - name: "Configuring yum repository"
    yum_repository:
        name: kubernetes
        description: kubernetes.repo
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        exclude: kubelet kubeadm kubectl

  - name: "Installing required Softwares:Docker,kubadm,kubectl,kubelet,iproute-tc"
    yum:
        name: "{{ item }}"
        state: present
        disable_excludes: kubernetes
    loop:
           - docker
           - iproute-tc
           - kubeadm

  - name: Starting Docker and Kubelet services
    service:
        name: "{{ item  }}"
        state: started
        enabled: yes
    loop:
        - docker
        - kubelet
  - name: kubeadm image pull
    command: "kubeadm config images pull"

  - name: Updating default drivers.
    copy:
        src: daemon.json
        dest: /etc/docker/daemon.json

  - name: Restarting docker services
    service:
        name: docker
        state: restarted
  - name: Updating k8s config file.
    copy:
      dest: /etc/sysctl.d/k8s.conf
      src: k8s.conf

  - name: Modifing kernel parameters
    command: "sysctl --system"

  - name: Joining k8 Cluster.
    shell: "{{ join_command }}"


